apiVersion: v1
kind: Service
metadata:
  name: exampledockerwebpage-service
  labels:
    app: exampledockerwebpage-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: example-docker-webpage
  sessionAffinity: None